# Chance for a custom mob to spawn, expressed as 0.0-1.0
# e.g. 0.01 is 1:1000
spawn_chance: 0.05

# A list of all supported custom mob IDs that are allowed to spawn naturally
spawn_naturally:
- drcuddles
- giant
- killerrabbit
- lordpuggleston
- mrskeltal
- sirmeowingtons